build:
  version: "2.0"

accounts:
  message: "Welcome to eazybank account QA related API"
  contactDetails:
    name: "John Doe - Tester"
    email: "john@eazyzbank.com"
  onLocalSupport:
    - (111) 555-1234
    - (222) 523-1345