build:
  version: "1.0"

cards:
  message: "Welcome to eazybank cards PROD related API"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazyzbank.com"
  onLocalSupport:
    - (999) 555-1234
    - (345) 523-1345