build:
  version: "1.0"

cards:
  message: "Welcome to eazybank cards related API"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazyzbank.com"
  onLocalSupport:
    - (555) 555-1234
    - (555) 523-1345