build:
  version: "2.0"

cards:
  message: "Welcome to eazybank cards QA related API"
  contactDetails:
    name: "John Doe - TESTER"
    email: "john@eazyzbank.com"
  onLocalSupport:
    - (333) 555-1234
    - (222) 523-1345