spring:
  application:
    name: "accounts"
    ## PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "prod"
  config:
#  cloud:
#    config:
#      uri: http://localhost:8071/
#      fail-fast: true
#      retry:
#        initial-interval: 3000
#        multiplier: 1.3
#        max-interval: 5000
#        max-attempts: 20
      import: "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Bank accounts application"
    version: "1.0.0"

endpoints:
  shutdown:
    enabled: true

grpc:
  client:
    loans:
      adress: discovery:///loans
      negotiationType: plaintext
    cards:
      adress: discovery:///cards
      negotiationType: plaintext
